# Projet immo / partie inf√©rence

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

In [3]:
df_fe = pd.read_pickle("data/EDA_iter_11_feature_engi.pkl")
df_fe

,id,longitude,latitude,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,...,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN,ratio_total_rooms/population,"group_house_age_0,10","group_house_age_10,20","group_house_age_20,30","group_house_age_30,40","group_house_age_40,50","group_house_age_50,60"
0,2072.0,-119.84,36.77,1853.0,473.0,1397.0,417.0,1.4817,72000.0,0.0,...,0.0,0.0,0.0,1.326414,1.0,0.0,0.0,0.0,0.0,0.0
1,10600.0,-117.80,33.68,2032.0,349.0,862.0,340.0,6.9133,274100.0,1.0,...,0.0,0.0,0.0,2.357309,1.0,0.0,0.0,0.0,0.0,0.0
2,2494.0,-120.19,36.60,875.0,214.0,931.0,214.0,1.5536,58300.0,0.0,...,0.0,0.0,0.0,0.939850,0.0,0.0,1.0,0.0,0.0,0.0
3,4284.0,-118.32,34.10,622.0,229.0,597.0,227.0,1.5284,200000.0,1.0,...,0.0,0.0,0.0,1.041876,0.0,0.0,0.0,1.0,0.0,0.0
4,16541.0,-121.23,37.79,1922.0,373.0,1130.0,372.0,4.0815,117900.0,0.0,...,0.0,0.0,0.0,1.700885,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16507,1099.0,-121.90,39.59,1465.0,278.0,745.0,250.0,3.0625,93800.0,0.0,...,0.0,0.0,0.0,1.966443,0.0,1.0,0.0,0.0,0.0,0.0
16508,18898.0,-122.25,38.11,2365.0,504.0,1131.0,458.0,2.6133,103100.0,0.0,...,0.0,1.0,0.0,2.091070,0.0,0.0,0.0,0.0,1.0,0.0
16509,11798.0,-121.22,38.92,2531.0,461.0,1206.0,429.0,4.4958,192600.0,0.0,...,0.0,0.0,0.0,2.098673,0.0,1.0,0.0,0.0,0.0,0.0
16510,6637.0,-118.14,34.16,2776.0,840.0,2546.0,773.0,2.5750,153500.0,1.0,...,0.0,0.0,0.0,1.090338,0.0,0.0,0.0,1.0,0.0,0.0
16511,2575.0,-124.13,40.80,2152.0,462.0,1259.0,420.0,2.2478,81100.0,0.0,...,0.0,0.0,1.0,1.709293,0.0,0.0,0.0,1.0,0.0,0.0

l'hypoth√®se de base est qu'il n'y a pas de corr√©lation entre une feature et la target

In [14]:
for i in df_fe:
    res = stats.pearsonr(df_fe[f"{i}"],df_fe["median_house_value"])
    print(i)
    print(res)

id
(0.06543466327224726, 3.8732105223907315e-17)
longitude
(-0.04675391553122152, 1.847642208365581e-09)
latitude
(-0.143969561680897, 3.494656395667405e-77)
total_rooms
(0.13321791658326362, 2.9571551303706847e-66)
total_bedrooms
(0.047894668371630957, 7.390881164155074e-10)
population
(-0.027441380116695432, 0.00042095163776829735)
households
(0.06324460701512734, 4.1398715693181713e-16)
median_income
(0.6896592006096155, 0.0)
median_house_value
(1.0, 0.0)
ocean_proximity_<1H OCEAN
(0.25901237210000316, 2.6088830340851604e-251)
ocean_proximity_INLAND
(-0.4880030271547037, 0.0)
ocean_proximity_ISLAND
(0.02663649410643465, 0.0006190861667978958)
ocean_proximity_NEAR BAY
(0.1596398135660152, 1.0931951572922123e-94)
ocean_proximity_NEAR OCEAN
(0.14292063964036092, 4.4470859442757224e-76)
ratio_total_rooms/population
(0.21077322947629631, 3.573575455707506e-165)
group_house_age_0,10
(-0.01452489003499134, 0.06198662722408942)
group_house_age_10,20
(-0.08097442523289046, 1.9788542886249943e-25)
group_house_age_20,30
(0.004096274817808571, 0.5986591587949732)
group_house_age_30,40
(7.176077340653036e-05, 0.9926432164308154)
group_house_age_40,50
(-0.0021133445385515615, 0.7859738461289058)
group_house_age_50,60
(0.15025925730875406, 5.539570201265529e-84)

In [13]:
for i in df_fe:
    res = stats.pearsonr(df_fe[f"{i}"],df_fe["median_house_value"])
    if res[1]>0.05 :
        print(i)
        print(res)

group_house_age_0,10
(-0.01452489003499134, 0.06198662722408942)
group_house_age_20,30
(0.004096274817808571, 0.5986591587949732)
group_house_age_30,40
(7.176077340653036e-05, 0.9926432164308154)
group_house_age_40,50
(-0.0021133445385515615, 0.7859738461289058)

In [ ]:
final_model = rfr.fit(df_fe.drop(columns = ['median_house_value']), df_fe["median_house_value"])

Nous avons ici 4 feature qui ne sont pas corr√©l√© a la target et statistiquement insignifiant